services:
  daily-scraper:
    image: sampad031/vahanscraper:daily-count-fetcher
    env_file:
      - .env.daily
    volumes:
      - ./logs/daily_scraper_logs:/app/logs
    working_dir: /app
    depends_on:
      - pg-server-1
    restart: unless-stopped

  pg-server-1:
    image: postgres
    environment:
      POSTGRES_USER: vahanfree
      POSTGRES_PASSWORD: vahanfree123
      POSTGRES_DB: vahanFreeDb
    ports:
      - "6543:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pg_data:

