services:

  daily-count-scraper:
    image: sampad031/vahanscraper:dailycountscraper2
    env_file:
      - .env.daily
    volumes:
      - /home/vahan/logs/daily_scraper_logs:/app/logs
    working_dir: /app
    restart: unless-stopped
    networks:
      - vahan-net
  
  daily-rto-scraper-tw-1:
    image: sampad031/vahanscrapermulti:07062025
    env_file:
      - .env.first.tw
    volumes:
      - /home/vahan/logs/logs_2025_1:/app/logs
      - /home/vahan/downloads:/app/downloads
      - /home/vahan/retries/retries_2025_1:/app/retries
      - ./source:/app/source
    working_dir: /app
    restart: unless-stopped
    networks:
      - vahan-net
  
  daily-rto-scraper-tw-2:
    image: sampad031/vahanscrapermulti:07062025
    env_file:
      - .env.second.tw
    volumes:
      - /home/vahan/logs/logs_2025_2:/app/logs
      - /home/vahan/downloads:/app/downloads
      - /home/vahan/retries/retries_2025_2:/app/retries
      - ./source:/app/source
    working_dir: /app
    restart: unless-stopped
    networks:
      - vahan-net
  
  daily-rto-scraper-tw-3:
    image: sampad031/vahanscrapermulti:07062025
    env_file:
      - .env.third.tw
    volumes:
      - /home/vahan/logs/logs_2025_3:/app/logs
      - /home/vahan/downloads:/app/downloads
      - /home/vahan/retries/retries_2025_3:/app/retries
      - ./source:/app/source
    working_dir: /app
    restart: unless-stopped
    networks:
      - vahan-net

  daily-rto-scraper-tw-4:
    image: sampad031/vahanscrapermulti:07062025
    env_file:
      - .env.fourth.tw
    volumes:
      - /home/vahan/logs/logs_2025_4:/app/logs
      - /home/vahan/downloads:/app/downloads
      - /home/vahan/retries/retries_2025_4:/app/retries
      - ./source:/app/source
    working_dir: /app
    restart: unless-stopped
    networks:
      - vahan-net
  
  daily-rto-scraper-tw-5:
    image: sampad031/vahanscrapermulti:07062025
    env_file:
      - .env.fifth.tw
    volumes:
      - /home/vahan/logs/logs_2025_5:/app/logs
      - /home/vahan/downloads:/app/downloads
      - /home/vahan/retries/retries_2025_5:/app/retries
      - ./source:/app/source
    working_dir: /app
    restart: unless-stopped
    networks:
      - vahan-net

  daily-rto-scraper-3w-1:
    image: sampad031/vahanscrapermulti:07062025
    env_file:
      - .env.first.3w
    volumes:
      - /home/vahan/logs/logs_2025_1:/app/logs
      - /home/vahan/downloads:/app/downloads
      - /home/vahan/retries/retries_2025_1:/app/retries
      - ./source:/app/source
    working_dir: /app
    restart: unless-stopped
    networks:
      - vahan-net
  
  daily-rto-scraper-3w-2:
    image: sampad031/vahanscrapermulti:07062025
    env_file:
      - .env.second.3w
    volumes:
      - /home/vahan/logs/logs_2025_2:/app/logs
      - /home/vahan/downloads:/app/downloads
      - /home/vahan/retries/retries_2025_2:/app/retries
      - ./source:/app/source
    working_dir: /app
    restart: unless-stopped
    networks:
      - vahan-net
  
  daily-rto-scraper-3w-3:
    image: sampad031/vahanscrapermulti:07062025
    env_file:
      - .env.third.3w
    volumes:
      - /home/vahan/logs/logs_2025_3:/app/logs
      - /home/vahan/downloads:/app/downloads
      - /home/vahan/retries/retries_2025_3:/app/retries
      - ./source:/app/source
    working_dir: /app
    restart: unless-stopped
    networks:
      - vahan-net

  daily-rto-scraper-3w-4:
    image: sampad031/vahanscrapermulti:07062025
    env_file:
      - .env.fourth.3w
    volumes:
      - /home/vahan/logs/logs_2025_4:/app/logs
      - /home/vahan/downloads:/app/downloads
      - /home/vahan/retries/retries_2025_4:/app/retries
      - ./source:/app/source
    working_dir: /app
    restart: unless-stopped
    networks:
      - vahan-net
  
  daily-rto-scraper-3w-5:
    image: sampad031/vahanscrapermulti:07062025
    env_file:
      - .env.fifth.3w
    volumes:
      - /home/vahan/logs/logs_2025_5:/app/logs
      - /home/vahan/downloads:/app/downloads
      - /home/vahan/retries/retries_2025_5:/app/retries
      - ./source:/app/source
    working_dir: /app
    restart: unless-stopped
    networks:
      - vahan-net


volumes:
  pg_data:

networks:
  vahan-net:
    external: true
