services:
  scraper2025-1:
    image: sampad031/vahanscraper:evmaster-may
    env_file:
      - .env.2024
    volumes:
      - ./logs_2025:/app/logs
      - ./downloads_2025:/app/downloads_2025
      - ./retries_2025:/app/retries
    working_dir: /app

  scraper2025-2:
    image: sampad031/vahanscraper:evmaster-may
    env_file:
      - .env.2025
    volumes:
      - ./logs_2025:/app/logs
      - ./downloads_2025:/app/downloads_2025
      - ./retries_2025:/app/retries
    working_dir: /app
