services: 
  custom-rto-scraper-1:
    image: sampad031/vahanscraper:rtoscraper04062025
    env_file:
      - .env.first
    volumes:
      - /home/vahan/logs/previous-year/logs_2024_1:/app/logs
      - /home/vahan/downloads:/app/downloads
      - /home/vahan/retries/previous-year/retries_2024_1:/app/retries
      - ./source:/app/source
    working_dir: /app
    restart: unless-stopped
    networks:
      - vahan-net
  
  custom-rto-scraper-2:
    image: sampad031/vahanscraper:rtoscraper04062025
    env_file:
      - .env.second
    volumes:
      - /home/vahan/logs/previous-year/logs_2024_2:/app/logs
      - /home/vahan/downloads:/app/downloads
      - /home/vahan/retries/previous-year/retries_2024_2:/app/retries
      - ./source:/app/source
    working_dir: /app
    restart: unless-stopped
    networks:
      - vahan-net
  
  custom-rto-scraper-3:
    image: sampad031/vahanscraper:rtoscraper04062025
    env_file:
      - .env.third
    volumes:
      - /home/vahan/logs/previous-year/logs_2024_3:/app/logs
      - /home/vahan/downloads:/app/downloads
      - /home/vahan/retries/previous-year/retries_2024_3:/app/retries
      - ./source:/app/source
    working_dir: /app
    restart: unless-stopped
    networks:
      - vahan-net

  custom-rto-scraper-4:
    image: sampad031/vahanscraper:rtoscraper04062025
    env_file:
      - .env.fourth
    volumes:
      - /home/vahan/logs/previous-year/logs_2024_4:/app/logs
      - /home/vahan/downloads:/app/downloads
      - /home/vahan/retries/previous-year/retries_2024_4:/app/retries
      - ./source:/app/source
    working_dir: /app
    restart: unless-stopped
    networks:
      - vahan-net

networks:
  vahan-net:
    external: true