services:

  pg-server:
    image: postgres
    environment:
      POSTGRES_USER: vahanfree
      POSTGRES_PASSWORD: vahanfree123
      POSTGRES_DB: vahanFreeDb
    ports:
      - "6543:6543"
    command: ["postgres", "-p", "6543"]
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - vahan-net

  daily-count-scraper:
    image: sampad031/vahanscraper:dailycountscraper
    env_file:
      - .env.daily
    volumes:
      - /home/vahan/logs/daily_scraper_logs:/app/logs
    working_dir: /app
    depends_on:
      - pg-server
    restart: unless-stopped
    networks:
      - vahan-net
  
  backend-server:
    image: sampad031/data-processor:3005
    env_file:
      - .env.backend
    ports:
      - "2525:2525"
    volumes:
      - /home/vahan/downloads:/application/downloads
    restart: unless-stopped
    networks:
      - vahan-net
    depends_on:
      - pg-server
  
  daily-rto-scraper-1:
    image: sampad031/vahanscraper:dailyrtoupdater2
    env_file:
      - .env.first
    volumes:
      - /home/vahan/logs/logs_2025_1:/app/logs
      - /home/vahan/downloads:/app/downloads
      - /home/vahan/retries/retries_2025_1:/app/retries
      - ./source:/app/source
    working_dir: /app
    restart: unless-stopped
    networks:
      - vahan-net
  
  daily-rto-scraper-2:
    image: sampad031/vahanscraper:dailyrtoupdater2
    env_file:
      - .env.second
    volumes:
      - /home/vahan/logs/logs_2025_2:/app/logs
      - /home/vahan/downloads:/app/downloads
      - /home/vahan/retries/retries_2025_2:/app/retries
      - ./source:/app/source
    working_dir: /app
    restart: unless-stopped
    networks:
      - vahan-net
  
  daily-rto-scraper-3:
    image: sampad031/vahanscraper:dailyrtoupdater2
    env_file:
      - .env.third
    volumes:
      - /home/vahan/logs/logs_2025_3:/app/logs
      - /home/vahan/downloads:/app/downloads
      - /home/vahan/retries/retries_2025_3:/app/retries
      - ./source:/app/source
    working_dir: /app
    restart: unless-stopped
    networks:
      - vahan-net

  daily-rto-scraper-4:
    image: sampad031/vahanscraper:dailyrtoupdater2
    env_file:
      - .env.fourth
    volumes:
      - /home/vahan/logs/logs_2025_4:/app/logs
      - /home/vahan/downloads:/app/downloads
      - /home/vahan/retries/retries_2025_4:/app/retries
      - ./source:/app/source
    working_dir: /app
    restart: unless-stopped
    networks:
      - vahan-net
  
  daily-rto-scraper-5:
    image: sampad031/vahanscraper:dailyrtoupdater2
    env_file:
      - .env.fourth
    volumes:
      - /home/vahan/logs/logs_2025_5:/app/logs
      - /home/vahan/downloads:/app/downloads
      - /home/vahan/retries/retries_2025_5:/app/retries
      - ./source:/app/source
    working_dir: /app
    restart: unless-stopped
    networks:
      - vahan-net

volumes:
  pg_data:

networks:
  vahan-net:
    name: vahan-net
    driver: bridge
