services:
  scraper2025-1:
    image: sampad031/vahanscraper:evmaster-latest
    env_file:
      - .env.2024
    volumes:
      - ./logs/logs_2025_1:/app/logs
      - ./downloads/downloads_2025_1:/app/downloads_2025
      - ./retries/retries_2025_1:/app/retries
    working_dir: /app

  scraper2025-2:
    image: sampad031/vahanscraper:evmaster-latest
    env_file:
      - .env.2025
    volumes:
      - ./logs/logs_2025_2:/app/logs
      - ./downloads/downloads_2025_2:/app/downloads_2025
      - ./retries/retries_2025_2:/app/retries
    working_dir: /app