services: 
  custom-rto-scraper-1:
    image: playwrightscraper:v1
    env_file:
      - .env.first
    volumes:
      - ./logs/previous-year/logs_2025_1:/app/logs
      - ./downloads:/app/downloads
      - ./retries/previous-year/retries_2025_1:/app/retries
      - ./source:/app/source
    working_dir: /app
    restart: unless-stopped
    # networks:
    #   - vahan-net
  
  custom-rto-scraper-2:
    image: playwrightscraper:v1
    env_file:
      - .env.second
    volumes:
      - ./logs/previous-year/logs_2025_2:/app/logs
      - ./downloads:/app/downloads
      - ./retries/previous-year/retries_2025_2:/app/retries
      - ./source:/app/source
    working_dir: /app
    restart: unless-stopped
    # networks:
    #   - vahan-net
  
  custom-rto-scraper-3:
    image: playwrightscraper:v1
    env_file:
      - .env.third
    volumes:
      - ./logs/previous-year/logs_2025_3:/app/logs
      - ./downloads:/app/downloads
      - ./retries/previous-year/retries_2025_3:/app/retries
      - ./source:/app/source
    working_dir: /app
    restart: unless-stopped
    # networks:
    #   - vahan-net

  custom-rto-scraper-4:
    image: playwrightscraper:v1
    env_file:
      - .env.fourth
    volumes:
      - ./logs/previous-year/logs_2025_4:/app/logs
      - ./downloads:/app/downloads
      - ./retries/previous-year/retries_2025_4:/app/retries
      - ./source:/app/source
    working_dir: /app
    restart: unless-stopped
    # networks:
    #   - vahan-net
  
  custom-rto-scraper-5:
    image: playwrightscraper:v1
    env_file:
      - .env.fifth
    volumes:
      - ./logs/previous-year/logs_2025_5:/app/logs
      - ./downloads:/app/downloads
      - ./retries/previous-year/retries_2025_5:/app/retries
      - ./source:/app/source
    working_dir: /app
    restart: unless-stopped
    # networks:
    #   - vahan-net

# networks:
  # vahan-net:
  #   external: true