services:
  pg-server:
    image: postgres
    environment:
      POSTGRES_USER: vahanfree
      POSTGRES_PASSWORD: vahanfree123
      POSTGRES_DB: vahanFreeDb
    ports:
      - "6543:6543"
    command: ["postgres", "-p", "6543"]
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - vahan-net
  
  backend-server:
    image: sampad031/data-processor:07062025
    env_file:
      - .env.backend
    ports:
      - "2525:2525"
    volumes:
      - /home/vahan/downloads:/application/downloads
    restart: unless-stopped
    networks:
      - vahan-net
    depends_on:
      - pg-server

volumes:
  pg_data:

networks:
  vahan-net:
    name: vahan-net
    driver: bridge
